### ISSUE TITLE
Ctor of hal-gpio

### ISSUE THREAD

**Issue by ValentiWorkLearning** [DrZlo13/black-midi2cv#4]
https://github.com/DrZlo13/black-midi2cv/blob/cbf133decfd469d29d88e232e654884a64c56ba2/app/hal/hal-gpio.cpp#L36

Just a simple:
```cpp
HalGpio::HalGpio(GPIO_TypeDef* port, uint16_t pin) :
m_port{port}, m_pin{pin}{}
```

**Comment by DrZlo13** [comment]
Done in d6ff64ed6e88d14c478251639223e428afe5b9dc
