### ISSUE TITLE
All of constants can be marked as constexpr inline.  

### ISSUE THREAD

**Issue by ValentiWorkLearning** [DrZlo13/black-midi2cv#5]
https://github.com/DrZlo13/black-midi2cv/blob/cbf133decfd469d29d88e232e654884a64c56ba2/app/midi/midi-config.h#L1
->
```cpp
constexpr inline std::uint8_t SYSEX_BUFFER_LEN  = 16;
```

**Comment by DrZlo13** [comment]
Done in 02fe5f07a9ba822991ede9ce306a27e8042f79dd
